# Generated by Django 4.0.5 on 2022-06-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='publish_date')),
                ('change_date', models.DateTimeField(verbose_name='change_date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDj.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDj.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDj.usermodel')),
            ],
        ),
    ]
