# Generated by Django 4.0.5 on 2022-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
