# Generated by Django 4.0.5 on 2022-06-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0003_blockedlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedList',
        ),
    ]
