# Generated by Django 4.0.5 on 2022-06-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0004_delete_blockedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked', to='labDj.usermodel')),
                ('user_blocking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocking', to='labDj.usermodel')),
            ],
        ),
    ]
