# Generated by Django 4.0.5 on 2022-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0005_blockedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
