# Generated by Django 4.0.5 on 2022-06-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0007_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
