# Generated by Django 4.0.5 on 2022-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0009_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
