# Generated by Django 4.0.5 on 2022-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0010_post_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profession',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
