# Generated by Django 4.0.5 on 2022-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0011_remove_post_profession_usermodel_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
            ],
        ),
    ]
