# Generated by Django 4.0.5 on 2022-06-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labDj', '0012_skils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skils',
            new_name='Skills',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labDj.skills'),
        ),
    ]
